### ISSUE TITLE
Only upload on change

### ISSUE THREAD

**Issue by gkoberger** [readmeio/github-readme-api-sync#15]
We should do a hash of the swagger file, and only upload if it's changed! Otherwise we're gonna end up messing up some stuff at some point... we don't want to be doing this every time someone pushes; we'll end up overwriting data or other weird stuff.

**Comment by erunion** [comment]
I saw this earlier today https://github.com/facade/ignition/pull/292/files#diff-87bf315b1f77e61de54992d0ed318d40R3-R7 which I think will only trigger a build when changes to those files are changed. That'd require the user to define their OAS file path though.
