### ISSUE TITLE
Show more info in ReadMe

### ISSUE THREAD

**Issue by gkoberger** [readmeio/github-readme-api-sync#16]
This isn't meant for this repo, but I wanted to keep everything in one place. We add the repo name and other info to the oas file when we upload it; it'd be great to surface it and link to the repo/action/etc from the ReadMe dashboard:

![image](https://user-images.githubusercontent.com/381393/87612421-5d06c780-c6bf-11ea-9570-97085d14a399.png)

**Comment by erunion** [comment]
We can add a `x-readme-source`-like header in the action to send along the repo that ran the workflow.
