### ISSUE TITLE
OpenAPI definition with references to external models

### ISSUE THREAD

**Issue by andreas-zapantis** [readmeio/github-readme-api-sync#46]
Hi All,

If i select to upload an OpenAPI definition which has references to models residing in another folder in the repo i get the following error during action execution:

```
Error: Error bundling your file: Error opening file "/home/runner/work/readmecom-trial/readmecom-trial/models/Pet.v1.yaml" 
ENOENT: no such file or directory, open '/home/runner/work/readmecom-trial/readmecom-trial/models/Pet.v1.yaml'
```

A sample method definition is looking like this:
```
paths:
  /pet:
    put:
      tags:
        - pet
      summary: Update an existing pet
      operationId: updatePet
      requestBody:
        description: Pet object that needs to be added to the store
        content:
          application/json:
            schema:
              $ref: ./models/Pet.v1.yaml
          application/xml:
            schema:
              $ref: ./models/Pet.v1.yaml
        required: true
```

My github action setup is like this:

```
name: Sync OAS to ReadMe
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: XXXX           
          oas-file-path: './api/petclinic.yaml'
          api-version: 'v1.0.0'
```

Nothing too fancy there. I tried searching around for other options but found nothing.
Is there a way i can get this to work with the github action?

**Comment by kanadgupta** [comment]
Hi @andreas-zapantis—sorry you're running into these issues. I'm having trouble figuring out if this is an issue with the [`actions/checkout`](https://github.com/actions/checkout) step since it's failing to locate your file, or if it's an issue with how [`oas-normalize`](https://github.com/readmeio/oas-normalize) [bundles external refs](https://github.com/readmeio/github-readme-sync/blob/e3edeac95c64a317b90f797e52f541813c405aab/main.js#L92). Any ideas @erunion?

**Comment by andreas-zapantis** [comment]
Hey @kanadgupta,
I do not think it is related to actions/checkout as I did the following to bypass the issue and it worked.
I moved petclinic.yaml from the api folder to the top level folder. Did the same with models and it worked.
So initially my folder layout was like this:
```
project/
  api/
    petclinic.yaml
    models/
      Pet.v1.yaml
```
This had the issue of locating models referenced in petclinic.yaml as specified in my original post.
Then i moved this to move everything one level up like this:
```
project/
  petclinic.yaml
  models/
    Pet.v1.yaml
```
This worked and model was discovered successfully from the action.
So i guess the issue is to how the path discovery works with references.

**Comment by kanadgupta** [comment]
Glad to hear you figured out a workaround, @andreas-zapantis!

I chatted with @erunion about it and what you're seeing is an internally known issue with the `oas-normalize` package around bundling external references. I just created an open issue in that repo that you can track: https://github.com/readmeio/oas-normalize/issues/99

Thanks again for flagging! We'll post updates to this issue as we have them.

**Comment by thibaudgirard** [comment]
Hi all 👋
I figure out the same issue when the root definition file is under a directory structure such as

```
project/
  directory/
    spec.yaml
    components/
      parameters.yaml
```

I saw that this was a known issue that should have been solved here https://github.com/readmeio/oas-normalize/pull/131, but I think the issue is still present as the action, in its latest version, return this error:
```
Error bundling your file: Error opening file "/runner/_work/project/components/parameters.yaml" 
```

Can anyone help me? 🙂

**Comment by kanadgupta** [comment]
Hi all! We recently kicked off plans to deprecate this repository entirely and add first-class GitHub Action support to [`rdme`](https://github.com/readmeio/rdme) (which includes support for external references and is overall far better maintained and feature-complete) 🚀

**EDIT**: our new GitHub Action is now live! You can check out our migration guide here: https://docs.readme.com/docs/automatically-sync-api-specification-with-github#migrating-to-rdme

**Comment by jdecool** [comment]
It seems that `rdme` external references support not working on my project.

My project stores all specs in `assets/openapi` directory with relative reference stored in `assets/openapi/components`.
I've tried to run `rdme openapi ./assets/openapi/spec.yaml --key=myKey --id=myId` and I've got this error:

```
rdme openapi ./assets/openapi/spec.yaml

Error opening file "[path]/components/parameters/Id.yaml"
ENOENT: no such file or directory, open '[path]/components/parameters/Id.yaml'
```

Relative files are stored in `[path]/assets/openapi/components/*`

**Comment by kanadgupta** [comment]
Hey folks! As mentioned above, we're deprecating this repository in favor of [our newest GitHub Action](https://docs.readme.com/docs/rdme) which has support for external references (and much more)!

Be sure to check out [our migration guide](https://docs.readme.com/docs/automatically-sync-api-specification-with-github#migrating-to-rdme) if you need a hand migrating your existing GitHub Action. If you still have any questions, feel free to [open up an issue in `rdme`](https://github.com/readmeio/rdme/issues/new) or [contact us via support](mailto:support@readme.io).

-Kanad and the ReadMe team 🦉
