### ISSUE TITLE
Cast to ObjectId failed for value":oid:" 

### ISSUE THREAD

**Issue by DmytroSH** [readmeio/github-readme-api-sync#7]
Run readmeio/github-readme-sync@1.0.3 ##[error]500 - "{\"error\":\"Cast to ObjectId failed for value \\\":oid:\\\" at path \\\"_id\\\" for model \\\"APISetting\\\"\"}"
Looks like something went wrong , just copy paste github actions from doc , and it fails

**Comment by erunion** [comment]
Sorry, this might be confusing documentation of the action on our part. Did you change `:oid:` in the action? `:oid:` shouldbe the ID we give you when you first upload an API definition to us.

**Comment by DmytroSH** [comment]
can i see oid from readme admin panel?yeah little bit confusing:)

**Comment by erunion** [comment]
In our dashboard on the "API Reference" page (https://dash.readme.io/project/yourProjectName/v1.0/reference), you'll see something like this:

![Screen Shot 2020-07-08 at 1 51 16 PM](https://user-images.githubusercontent.com/33762/86969205-47732a00-c122-11ea-8618-a8980d9ad92a.png)

The ID listed there is what you can use as `:oid:`. So if my ID were `abcdef12345`, the `readme-api-id` config in my workflow would look like:

```
readme-api-id: 'abcdef12345'
```

I'll make sure out action documentation on https://docs.readme.com/guides/docs/automatically-sync-api-specification-with-github is updated to make this a little clearer.
